version: '3.9'

# docker network create kcm-net
networks:
  default:
    external:
      name: kcm-net

services:

  # -------------------------
  # Controllers (KRaft)
  # -------------------------
  controller-1:
    image: apache/kafka:latest
    container_name: controller-1
    ports: ["19093:9093"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller1-data:/var/lib/kafka/data

  controller-2:
    image: apache/kafka:latest
    container_name: controller-2
    ports: ["29093:9093"]
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller2-data:/var/lib/kafka/data

  controller-3:
    image: apache/kafka:latest
    container_name: controller-3
    ports: ["39093:9093"]
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - controller3-data:/var/lib/kafka/data

  # -------------------------
  # Brokers (TLS + SASL/SCRAM)
  # -------------------------
  broker-1:
    image: apache/kafka:latest
    container_name: broker-1
    ports:
      - "9493:9493"    # SASL_SSL_HOST (client access)
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093

      # Listeners: ONLY SASL_SSL (no PLAINTEXT)
      KAFKA_LISTENERS: SASL_SSL_INTERNAL://:9092,SASL_SSL_HOST://:9493
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL_INTERNAL://broker-1:9092,SASL_SSL_HOST://localhost:9493
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # SASL/SCRAM
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512

      # TLS
      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit

      # JAAS (inter-broker)
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"

      # ACLs (authorizer actif mais permissif pour démarrer)
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - broker1-data:/var/lib/kafka/data
      - ./certificates/broker-1:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on: [controller-1, controller-2, controller-3]

  broker-2:
    image: apache/kafka:latest
    container_name: broker-2
    ports:
      - "9593:9593"
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093

      KAFKA_LISTENERS: SASL_SSL_INTERNAL://:9092,SASL_SSL_HOST://:9593
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL_INTERNAL://broker-2:9092,SASL_SSL_HOST://localhost:9593
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512

      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit

      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"

      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - broker2-data:/var/lib/kafka/data
      - ./certificates/broker-2:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on: [controller-1, controller-2, controller-3]

  broker-3:
    image: apache/kafka:latest
    container_name: broker-3
    ports:
      - "9693:9693"
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093

      KAFKA_LISTENERS: SASL_SSL_INTERNAL://:9092,SASL_SSL_HOST://:9693
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL_INTERNAL://broker-3:9092,SASL_SSL_HOST://localhost:9693
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,SASL_SSL_INTERNAL:SASL_SSL,SASL_SSL_HOST:SASL_SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_SSL_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512,PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512

      KAFKA_SSL_KEYSTORE_LOCATION: /var/private/ssl/kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_TRUSTSTORE_LOCATION: /var/private/ssl/kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit

      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas.conf"

      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    volumes:
      - broker3-data:/var/lib/kafka/data
      - ./certificates/broker-3:/var/private/ssl
      - ./jaas.conf:/etc/kafka/jaas.conf
    depends_on: [controller-1, controller-2, controller-3]

volumes:
  controller1-data:
  controller2-data:
  controller3-data:
  broker1-data:
  broker2-data:
  broker3-data:
